# Generated by Django 3.2.4 on 2021-07-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_commande_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=250)),
                ('ppa', models.DecimalField(decimal_places=2, max_digits=7)),
                ('marge', models.IntegerField(default=20)),
            ],
        ),
    ]
