# Generated by Django 3.2.4 on 2021-07-14 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='marge',
        ),
        migrations.RemoveField(
            model_name='products',
            name='ppa',
        ),
    ]
