# Generated by Django 3.2.4 on 2021-07-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tag',
            field=models.CharField(default='Médicament', max_length=50),
        ),
    ]
