# Generated by Django 3.2.4 on 2021-07-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_products_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='marge',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='products',
            name='ppa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='products',
            name='pu',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
