# Generated by Django 3.2.4 on 2021-07-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20210722_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='productype',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
