# Generated by Django 3.2.4 on 2021-08-04 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_commande_qtt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='qtt',
        ),
        migrations.RemoveField(
            model_name='products',
            name='marge',
        ),
        migrations.RemoveField(
            model_name='products',
            name='ppa',
        ),
        migrations.RemoveField(
            model_name='products',
            name='pu',
        ),
    ]
